### ISSUE TITLE
如何修改默认路由

### ISSUE THREAD

**Issue by cfxisrich** [Shiotsukikaedesari/vis-resm-ui#1]
大佬你好，我想把默认的路由“http://127.0.0.1:4173/test/index.html” 修改成  “http://127.0.0.1:4173/public/index.html”，有试过在package.json指定文件，也有试过加router.js，都没有作用，请问应该怎么修改呢

**Comment by Shiotsukikaedesari** [comment]
这个是开发组件用的脚手架，按设计来讲不存在需要修改默认路由的需求，index.html只是一个测试页面。

**Comment by cfxisrich** [comment]
是这样的，我想在3D精灵嵌入一个播放器组件，然后在组件编写的时候把.js依赖等文件放在了pibilc目录下，然后组件单独运行时，是可以正常的，导入到编辑器后，public下的js依赖文件识别不到，所以才会去想改路由，请问这种情况是什么问题

**Comment by Shiotsukikaedesari** [comment]
如果js资源是静态资源不会通过build，静态资源地址用URL类和import.mate.url获取，如果是需要过build的，放在public下不合适。

**Comment by cfxisrich** [comment]
对的，是静态资源，具体情况是这样的，引入了这三个文件
![image](https://github.com/Shiotsukikaedesari/vis-resm-ui/assets/89836473/958fe63f-1071-49fb-9415-7c4d00664cb0)
然后在index.html中也有获取
![image](https://github.com/Shiotsukikaedesari/vis-resm-ui/assets/89836473/e2cf046c-a3d8-487e-9663-91b257233669)
index.vue中也有引入
![image](https://github.com/Shiotsukikaedesari/vis-resm-ui/assets/89836473/191c74ef-2282-46f8-bf34-9e7eeb1cf15c)
打包上传到编辑器后，把UI组件拖到3D精灵中还是会报错找不到资源
![image](https://github.com/Shiotsukikaedesari/vis-resm-ui/assets/89836473/56a9ae90-3d02-46a7-82b8-0741c214c50b)

**Comment by cfxisrich** [comment]
对的，是静态资源，具体情况是这样的，引入了这三个文件

然后在index.html中也有获取

index.vue中也有引入

打包上传到编辑器后，把UI组件拖到3D精灵中还是会报错找不到资源

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shiotsukikaedesari/vis-resm-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月19日(星期一) 上午10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Shiotsukikaedesari/vis-resm-ui] 如何修改默认路由 (Issue #1)





 
如果js资源是静态资源不会通过build，静态资源地址用URL类和import.mate.url获取，如果是需要过build的，放在public下不合适。

**Comment by cfxisrich** [comment]
对了还有一个我没说清楚，我使用 npm run preview 是可以正常预览播放，使用npm run dev命令启动时也是会报错
![image](https://github.com/Shiotsukikaedesari/vis-resm-ui/assets/89836473/0f9131d5-087e-41c3-b00c-10e609d34d3b)
不过刷新一下就正常了

**Comment by Shiotsukikaedesari** [comment]
你需要使用esm模式引入资源，你上面的引入模式是iife，这是一点。其次组件化开发目标是一个vue组件，构建后的产物是不包含index.html文件的，也就是之前说的index.html只是一个测试用的页面。所以你需要按照组件模块开发思维来进行。

**Comment by Shiotsukikaedesari** [comment]
关于如何动态引入iife，你可以再组件生命周期中通过URL和import.mate.url动态获取地址，然后动态创建script dom插入。

**Comment by cfxisrich** [comment]
好嘞，我明白了怎么做了，谢谢大佬的指导

**Comment by cfxisrich** [comment]
好嘞，我明白怎么做了，谢谢大佬的指导


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shiotsukikaedesari/vis-resm-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月19日(星期一) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Shiotsukikaedesari/vis-resm-ui] 如何修改默认路由 (Issue #1)





 
关于如何动态引入iife，你可以再组件生命周期中通过URL和import.mate.url动态获取地址，然后动态创建script dom插入。
